spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size:  50MB
  jackson:
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: NON_NULL
  profiles:
    active: dev

server:
  port: 8888
  tomcat:
    max-threads: 1000