server:
  port: 8888
  tomcat:
      accept-count: 1000
      max-threads: 1000
      max-connections: 1000
      min-spare-threads: 20
      uri-encoding: UTF-8

spring:
  freemarker:
    suffix: .html
    settings:
      tag_syntax: auto_detect
      object_wrapper: freemarker.ext.beans.BeansWrapper
