spring:
  profiles:
    active: dev
  data:
    elasticsearch:
      cluster-nodes: 192.168.31.128:9300

server:
  port: 8088
  tomcat:
      accept-count: 1000
      max-threads: 1000
      max-connections: 1000
      min-spare-threads: 20
      uri-encoding: UTF-8